### ISSUE TITLE
Build failed on mac

### ISSUE THREAD

**Issue by salusijf** [lemonsqueeze/gogui#2]
hello,

Build failed on mac (Mojave)
/Users/pete/Downloads/gogui-master/build.xml:376: Execute failed: java.io.IOException: Cannot run program "/Developer/Tools/SetFile" (in directory "/Users/pete/Downloads/gogui-master"): error=2, No such file or directory

thanks

**Comment by lemonsqueeze** [comment]
Hi,
No idea what's going on, maybe someone who has a mac can help.
In the worst case it's always possible to build on another platform and copy the .jar's over...

**Comment by salusijf** [comment]
Ok. Thanks.
I run it on Windows10 with a VM.
